services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
      - ./init-user.sql:/container-entrypoint-initdb.d/init-user.sql
      - oracle-data:/opt/oracle/oradata
    networks:
      - oracle-network

networks:
  oracle-network:
    driver: bridge

volumes:
  oracle-data:
    driver: local


